### ISSUE TITLE
java('com.demo.SomeObject', null)

### ISSUE THREAD

**Issue by fengmk2** [node-modules/js-to-java#12]
https://github.com/node-modules/js-to-java/blob/master/index.js#L10

`java('com.demo.SomeObject', null)` => 

```js
{
  $class: 'com.demo.SomeObject',
  $value: null
}
```

but this is a bug, because java server want:

`java('com.demo.SomeObject', null)` => `null`

**Comment by fengmk2** [comment]
@coolme200 I saw #7 change this logic.

**Comment by gxcsoccer** [comment]
:+1:   

It's really confused me.
