### ISSUE TITLE
日期类型怎么转换？

### ISSUE THREAD

**Issue by git-lt** [node-modules/js-to-java#47]

**Comment by panxia** [comment]
hi，
我发现你的API中没有定义对象 数组这个类型：
比如String[] Integer[]  Object[]这种参数不知道该怎么传？
 var arg2=java.array('java.lang.String',["firstCatItemId","thridCatItemId","shopItemId","brandItemId"]);这样吗？

**Comment by chua1989** [comment]
同问

**Comment by hufeng** [comment]
hessian.js 直接支持writeDate(new Date()) 或者writeDate(Date.now())

**Comment by creasy2010** [comment]
hessian.js 可以识别Date类型. 直接放到对象即可...

**Comment by gxcsoccer** [comment]
如果传入的是 Date 对象的化，不用转换

```js
const hessian = require('hessian.js');
const buf = hessian.encode(new Date(), '2.0');
```

如果传入的是 Number，需要转换如下

```js
const java = require('js-to-java');
const hessian = require('hessian.js');

const arg = java('java.util.Date', Date.now());
const buf = hessian.encode(arg, '2.0');
```
