### ISSUE TITLE
java.String bug

### ISSUE THREAD

**Issue by oklai** [node-modules/js-to-java#5]
```js
java.String(1);
// return { '$class': 'java.lang.String', '$': 1 }

java.String('1');
// return { '$class': 'java.lang.String', '$': '1' }
```
如果参数值是int，结果转换后的类型值也是int。
正确的预期是转换后会自动把int转为string，不过是`1`还是`'1'`，其结果都应该是`'1'`.

**Comment by dead-horse** [comment]
这个模块不会做类型转换，cc @coolme200 做类型转换会不会有问题？

**Comment by oklai** [comment]
如果不做转换，建议检测传入的类型，如果类型不正确则抛出错误，这样可以提前避免错误。

**Comment by dead-horse** [comment]
@coolme200 是否可能出现 `java.Integer(null)` 的情况？

**Comment by coolme200** [comment]
我看下

**Comment by coolme200** [comment]
看了下 Hessian 的实现，如果是空值，直接 writeNull()，那我们的 js-to-java 可以改下 

```
java.Integer(null)  --> return null;
```

**Comment by coolme200** [comment]
我们之前 
```
{
  $class: 'java.lang.Integer',
  $: null
}
```

这样是错的。

**Comment by coolme200** [comment]
至于类型转换，最好当然是在这里做掉，java.String 那理所当然传进去的应该就是 string。

工具类不做，业务也肯定要做，上面提到的几个问题我统一做下。

**Comment by dead-horse** [comment]
good

**Comment by coolme200** [comment]
如果传 NaN hessian.js 报  

hessian writeInt expect input type is `int32`, but got `number`

如果传 "a"

hessian writeInt expect input type is `int32`, but got `string`

**Comment by dead-horse** [comment]
typeof NaN === 'number' ... 估计 hessian 里面需要针对他做个判断

**Comment by fengmk2** [comment]
close by https://github.com/node-modules/js-to-java/pull/7/files
